version: 0.0
os: linux
hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_app.sh
      timeout: 300
