version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Entered the install phase...
      - echo Check java version...
      - java -version
      - echo Validate docker
      - docker ps
      - docker images
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Check java version...
      - java -version
  build:
    commands:
      - echo Build phase...
      - echo Compile and running tests using Gradle Wrapper...
      - chmod +x gradlew
      - ./gradlew build -x test
      - echo Build Docker image and tag it...
      - docker build -t bryanvalencia94/petclinic:$CODEBUILD_BUILD_NUMBER .
  post_build:
    commands:
      - echo Post-build phase...
      - echo Push Docker image to repository...
      - docker login -u bryanvalencia94 -p $DOCKER_AUTH_TOKEN
      - docker push bryanvalencia94/petclinic:$CODEBUILD_BUILD_NUMBER

#artifacts:
#  files:
#    - '**/*'
#  name: DevOpsAppArtifacts
