version: 0.2

env:
  exported-variables:
    - CODEBUILD_RESOLVED_SOURCE_VERSION
  secrets-manager:
    DOCKER_AUTH_TOKEN: "GIT_HUB_CREDENTIALS:DOCKER_AUTH_TOKEN"
    DOCKER_USERNAME: "GIT_HUB_CREDENTIALS:DOCKER_USERNAME"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Entered the install phase...
      - echo Check java version...
      - java -version
      - echo Validate docker
      - docker ps
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Check java version...
      - java -version
  build:
    commands:
      - echo Build phase...
      - echo Compile and running tests using Gradle Wrapper...
      - chmod +x gradlew
      - ./gradlew build -x test
      - echo Build Docker image and tag it...
      - docker build -t bryanvalencia94/petclinic:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - echo Post-build phase...
      - echo Push Docker image to repository...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_AUTH_TOKEN
      - docker push bryanvalencia94/petclinic:$CODEBUILD_RESOLVED_SOURCE_VERSION

outputs:
  SOURCE_VERSION:
    value: ${CODEBUILD_SOURCE_VERSION}
#artifacts:
#  files:
#    - '**/*'
#  name: DevOpsAppArtifacts
